/* Import of the Link component from React Router to render functionality to the nav buttons */
import { Link } from 'react-router-dom';

/* Import of main stylesheet generated by the SCSS files and preprocessor */
import '../scss/main.css';

/* Definition of the Header components that will appear on all renders */
export const Header = () => {
    return (
        <div className={'header-container'}>
            <Link
                to={'/'}
                className={'header-title'}
            >
                <h1>Maintenance Management System (MMS)</h1>
            </Link>
            <div className={'header-navigation'}>
                <Link
                    to={'/submitJob'}
                >
                    <button className={'btn btn-nav'}>
                        Submit Job
                    </button>
                </Link>
                <Link
                    to={'/listJobs'}
                >
                    <button className={'btn btn-nav'}>
                        List Jobs
                    </button>
                </Link>
                <Link
                    to={'/filterJobsByStatus'}
                >
                    <button className={'btn btn-nav'}>
                        Filter By Status
                    </button>
                </Link>
                <Link
                    to={'/updateInfoOfJob'}
                >
                    <button className={'btn btn-nav'}>
                        Update Job
                    </button>
                </Link>
                <Link
                    to={'/updateStatusMultipleJobs'}
                >
                    <button className={'btn btn-nav'}>
                        Update Status (Multiple)
                    </button>
                </Link>
                <Link
                    to={'/archiveJob'}
                >
                    <button className={'btn btn-nav'}>
                        Archive Job
                    </button>
                </Link>

            </div>
        </div>
    )
}