/* Import of the React hooks needed in this component */
import {useEffect, useState} from "react";

/* Import of main stylesheet generated by SCSS and preprocessor */
import '../scss/main.css';

/* Definition of the SubmitJob component that will be used to initially complete details
* about and submit a job for tracking */
export const SubmitJob = () => {

    /* Declaration and initialisation of state variables needed */
    const [date, setDate] = useState('');
    const [description, setDescription] = useState('');
    const [location, setLocation] = useState('');
    const [priority, setPriority] = useState('');
    const [status, setStatus] = useState('');

    const radioButtonHandler = (event) => {
        setPriority(event.target.value);

    }

    const submitHandler = (event) => {
        event.preventDefault();
        setStatus('Submitted');


    }

    useEffect(() => {

    })

    return (
        <div className={'submit-job-container'}>
            <form onSubmit={submitHandler}>
                <label htmlFor={'date'}>
                    Date:
                    <input
                        type={'date'}
                        id={'date'}
                        name={'date'}
                        value={date}
                        onChange={(event) => setDate(event.target.value)}
                    />
                </label>
                <label htmlFor={'description'}>
                    Description:
                    <input
                        type={'text'}
                        id={'description'}
                        name={'description'}
                        value={description}
                        placeholder={'Description'}
                        onChange={(event) => setDescription(event.target.value)}
                    />
                </label>
                <label htmlFor={'location'}>
                    Location:
                    <input
                        type={'text'}
                        id={'location'}
                        name={'location'}
                        value={location}
                        placeholder={'Location'}
                        onChange={(event) => setLocation(event.target.value)}
                    />
                </label>
                <p>Priority</p>
                <label
                    htmlFor={'urgent'}
                    className={'label-radio'}
                >
                    Urgent
                    <input
                        type={'radio'}
                        id={'urgent'}
                        name={'priority'}
                        value={'urgent'}
                        onChange={radioButtonHandler}
                        checked={priority === 'urgent'}
                    />
                </label>
                <label
                    htmlFor={'routine'}
                    className={'label-radio'}
                >
                    Routine
                    <input
                        type={'radio'}
                        id={'routine'}
                        name={'priority'}
                        value={'routine'}
                        onChange={radioButtonHandler}
                        checked={priority === 'routine'}
                    />
                </label>
                <input
                    className={'btn-submit'}
                    type={'submit'}
                    value={'Submit'}
                />
            </form>
        </div>
    )
}