/* Import of the React hooks needed in this component */
import {useState} from "react";
/* Import of the axios client to handle API requests to the backend */
import axios from 'axios';

/* Import of main stylesheet generated by SCSS and preprocessor */
import '../scss/main.css';

/* Definition of the SubmitJob component that will be used to initially complete details
* about and submit a job for tracking */
export const SubmitJob = () => {

    /* Declaration and initialisation of state variables needed */
    const [date, setDate] = useState('');
    const [description, setDescription] = useState('');
    const [location, setLocation] = useState('');
    const [priority, setPriority] = useState('');

    /* The change handler for the radio buttons for priority of the request */
    const radioButtonHandler = (event) => {
        setPriority(event.target.value);

    }

    /* The form's submit handler which also changes the status to 'Submitted' */
    const submitHandler = (event) => {

        /* Configurations for the axios request to the backend that will send the information to be
        * stored in the database */
        const url = 'http://localhost:8000/saveNewJob';
        const config = {
            date: date,
            description: description,
            location: location,
            priority: priority,
        }

        /* The axios request to the backend */
        axios.post(url, config)
            .then(response => {
                return response.data
            })
            .catch(error => {
                console.log('Error', error.message);
            })
    }

    /* The rendering of the submit job input form */
    return (
        <div className={'submit-job-container'}>
            <form onSubmit={submitHandler}>
                <label htmlFor={'date'}>
                    Date:
                    <input
                        type={'date'}
                        id={'date'}
                        name={'date'}
                        onChange={(event) => setDate(event.target.value)}
                        required
                    />
                </label>
                <label htmlFor={'description'}>
                    Description:
                    <input
                        type={'text'}
                        id={'description'}
                        name={'description'}
                        placeholder={'Description'}
                        onChange={(event) => setDescription(event.target.value)}
                        required
                    />
                </label>
                <label htmlFor={'location'}>
                    Location:
                    <input
                        type={'text'}
                        id={'location'}
                        name={'location'}
                        placeholder={'Location'}
                        onChange={(event) => setLocation(event.target.value)}
                        required
                    />
                </label>
                <p>Priority</p>
                <label
                    htmlFor={'urgent'}
                    className={'label-radio'}
                >
                    Urgent
                    <input
                        type={'radio'}
                        id={'urgent'}
                        name={'priority'}
                        value={'urgent'}
                        onChange={radioButtonHandler}
                        // checked={priority === 'urgent'}
                    />
                </label>
                <label
                    htmlFor={'routine'}
                    className={'label-radio'}
                >
                    Routine
                    <input
                        type={'radio'}
                        id={'routine'}
                        name={'priority'}
                        value={'routine'}
                        onChange={radioButtonHandler}
                        // checked={priority === 'routine'}
                    />
                </label>
                <input
                    className={'btn-submit'}
                    type={'submit'}
                    value={'Submit'}
                />
            </form>
        </div>
    )
}