/* Import of the React hooks needed in this component */
import {useState} from "react";
/* Import of the axios client to handle API requests to the backend */
import axios from 'axios';

/* Import of main stylesheet generated by SCSS and preprocessor */
import '../scss/main.css';

/* Definition of the SubmitJob component that will be used to initially complete details
* about and submit a job for tracking */
export const SubmitJob = () => {

    /* Declaration and initialisation of state variables needed */
    const [date, setDate] = useState('');
    const [description, setDescription] = useState('');
    const [location, setLocation] = useState('');
    const [priority, setPriority] = useState('');
    const [status, setStatus] = useState('');


    /* The change handler for the radio buttons for priority of the request */
    const radioButtonHandler = (event) => {
        setPriority(event.target.value);
    }

    const selectHandler = (event) => {
        setStatus(event.target.value);
    }

    /* The form's submit handler which also changes the status to 'Submitted' */
    const submitHandler = (event) => {

        setStatus('Submitted');
        console.log('click')
        /* Configurations for the axios request to the backend that will send the information to be
        * stored in the database */
        const url = 'http://localhost:8000/saveNewJob';
        const config = {
            date: date,
            description: description,
            location: location,
            priority: priority,
            status: status
        }

        /* The axios request to the backend */
        axios.post(url, config)
            .then(response => {
                return response.data
            })
            .catch(error => {
                console.log('Error', error.message);
            })
    }

    /* The rendering of the submit job input form */
    return (
        <div className={'submit-job-container'}>
            <h1 className={'section-titles'}>Submit Task</h1>
            <form
                className={'submit-form'}
                onSubmit={submitHandler}
            >
                <div className={'submit-form-textfields'}>
                    <label htmlFor={'date'}>
                        Date:
                        <input
                            type={'date'}
                            id={'date'}
                            name={'date'}
                            onChange={(event) => setDate(new Date(event.target.value))}
                            required
                        />
                    </label>
                    <label htmlFor={'description'}>
                        Description:
                        <input
                            type={'text'}
                            id={'description'}
                            name={'description'}
                            placeholder={'Description'}
                            onChange={(event) => setDescription(event.target.value)}
                            style={{
                                fontWeight: 900,
                                color: '#800000'
                            }}
                            required
                        />
                    </label>
                    <label htmlFor={'location'}>
                        Location:
                        <input
                            type={'text'}
                            id={'location'}
                            name={'location'}
                            placeholder={'Location'}
                            onChange={(event) => setLocation(event.target.value)}
                            style={{
                                fontWeight: 900,
                                color: '#800000'
                            }}
                            required
                        />
                    </label>
                </div>
                {/*<p>Priority</p>*/}

                <div className={'submit-form-radio-buttons'}>
                    <p>Priority</p>
                    <label
                        htmlFor={'urgent'}
                        className={'label-radio'}
                    >
                        Urgent
                        <input
                            type={'radio'}
                            id={'urgent'}
                            name={'priority'}
                            value={'Urgent'}
                            onChange={radioButtonHandler}
                            // checked={priority === 'urgent'}
                        />
                    </label>
                    <label
                        htmlFor={'routine'}
                        className={'label-radio'}
                        /* Inline style to override React-Bootstrap interference */
                        style={{marginLeft: 1 + 'rem'}}
                    >
                        Routine
                        <input
                            className={'radio-second'}
                            type={'radio'}
                            id={'routine'}
                            name={'priority'}
                            value={'Routine'}
                            onChange={radioButtonHandler}
                            // checked={priority === 'routine'}
                        />
                    </label>
                </div>
                <div className={'submit-form-select'}>
                    <label
                        htmlFor={'status'}
                        className={'select-label'}
                        /* Inline styling to override React-Bootstrap default styles */
                        style={{
                            marginTop: 1 + 'rem',
                            marginLeft: 4 + 'rem'
                        }}
                    >
                        Status:
                        <select
                            id={'status'}
                            name={'status'}
                            onChange={selectHandler}
                            style={{
                                fontWeight: 900,
                                color: '#800000'
                            }}
                        >
                            <option>--Select--</option>
                            <option value={'Submitted'}>Submitted</option>
                            <option value={'In progress'}>In progress</option>
                            <option value={'Completed'}>Completed</option>
                        </select>
                    </label></div>
                <input
                    className={'btn-submit'}
                    type={'submit'}
                    value={'Submit'}
                />
            </form>
        </div>
    )
}