/* Import of Routes and Route needed to setup the React Router routes of the page */
import { Routes, Route } from 'react-router-dom';

/* Import of the components needed in the App component and for the routes */
import { Header } from "./components/Header";
import { LandingPage } from "./components/LandingPage";
import { ArchiveJob } from "./components/ArchiveJob";
import { ListJobsByDate } from "./components/ListJobsByDate";
import { SubmitJob } from "./components/SubmitJob";
import { UpdateInfoOfJob } from "./components/UpdateInfoOfJob";
import { UpdateStatusMultipleJobs } from "./components/UpdateStatusMultipleJobs";
import { ListJobsByStatus } from "./components/ListJobsByStatus";
import {UpdateJobForm} from "./components/UpdateJobForm";
import {FilterJobsByStatus} from "./components/FilterJobsByStatus";
import {ViewArchive} from "./components/ViewArchive";

/* Import of the main stylesheet generated by the SCSS files and preprocessor */
import './scss/main.css';
/* Import of local stylesheet to resolve background image to be displayed on all renders */
import './App.css';

/* Definition of the main component of the application */
export const App = () => {
    return (
        <div className="App">
            <Header/>
            {/* Setup of React Router system */}
            <Routes>
                <Route path={'/'} element={<LandingPage/>} exact/>
                <Route path={'/archiveJob'} element={<ArchiveJob/>}/>
                <Route path={'/listJobsByStatus'} element={<ListJobsByStatus/>}/>
                <Route path={'/filterJobsByStatus'} element={<FilterJobsByStatus/>}/>
                <Route path={'/listJobs'} element={<ListJobsByDate/>}/>
                <Route path={'/submitJob'} element={<SubmitJob/>}/>
                <Route path={'/updateInfoOfJob'} element={<UpdateInfoOfJob/>}/>
                <Route path={'/updateJobForm'} element={<UpdateJobForm/>} />
                <Route path={'/updateStatusMultipleJobs'} element={<UpdateStatusMultipleJobs/>}/>
                <Route path={'/viewArchive'} element={<ViewArchive/>}/>

            </Routes>
        </div>
    );
}

