/* Import of the modules needed to render the main App component */
import React from 'react';
import ReactDOM from 'react-dom/client';

/* Import of the BrowserRouter from react-router-dom */
import {BrowserRouter} from 'react-router-dom';

/* Import of the App component */
import {App} from './App';

/* Import of the main stylesheet generated by the SCSS files and preprocessor */
import './scss/main.css';

/* Render of the main App component in the div with id 'root' on the index.html page */
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <App/>
        </BrowserRouter>
    </React.StrictMode>
);
